# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/shinshin8/myFavorite_backend
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...