[Database]
DriverName = "mysql"
User = "my_favorite"
Password = "my_favorite"
Database = "my_favorite"
Host = "127.0.0.1"
DbPort = "3306"

[Port]
Port = ":8080"

[Redis]
RedisAddress = "redis://localhost"

[LogFile]
LogFile = "./all-the-logs.log"