[Database]
DriverName = "mysql"
User = "my_favorite"
Password = "my_favorite"
Database = "my_favorite"
Host = "127.0.0.1"
DbPort = "3306"

[Port]
Port = ":8080"

[LogFile]
LogFile = "./all-the-logs.log"

[TokenString]
TokenString = "98d69b24b593dd2c04039ec2a724961b0393ed2cdf96e80cb6231614515f45cd"